AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TelegramToken:
    Description: 'Token for Telegram Bot API as received from the BotFather'
    Type: String
    NoEcho: true
  AdminTelegramUsername:
    Description: "Username of the bot's administrator on Telegram"
    Type: String
  AllocatedStorageDB:
    Description: 'Storage allocated for the settings database'
    Type: String
    Default: '20'

Resources:
  AudioStoragePolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref AudioStorage
      PolicyDocument:
        Statement:
          Action:
          - 's3:*'
          Effect: Allow
          Resource: !Join ['', ['arn:aws:s3:::', !Ref AudioStorage, '/*']]
          Principal: '*'

  FeedUpdatesQueue:
    Type: 'AWS::SQS::Queue'
    Properties: {}
  AudioStorage:
    Type: 'AWS::S3::Bucket'
    Properties: {}
  SettingsDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: postgres
      EngineVersion: '10.5'
      DBInstanceClass: db.t2.micro
      DBName: 'rss2tg'
      MasterUsername: 'rss2tg'
      MasterUserPassword: 'rss2tg1234'
      AllocatedStorage: !Ref AllocatedStorageDB

  BotInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      Environment:
        Variables:
          TG_TOKEN: !Ref TelegramToken
          TG_ADMIN: !Ref AdminTelegramUsername
    DependsOn:
    - AudioStorage
    - FeedUpdatesQueue
    - SettingsDB
    Metadata:
        AWS::CloudFormation::Init:
          sources:
            ~/project/ : "https://github.com/vilunov/aws-rss2speech/tarball/master"
          commands:
            deploy_bot:
              command: "python ~/project/bot/bot.py"
              env:
                AWS_BUCKET: !Ref AudioStorage
                AWS_SQS_QUEUE_URL: !Ref FeedUpdatesQueue
                DB_HOSTNAME: !GetAtt SettingsDB.Endpoint.Address
                DB_HOSTPORT: !GetAtt SettingsDB.Endpoint.Port

  FeedUpdater:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: lambda.zip
      Runtime: python3.6
      Environment:
        Variables:
          AWS_BUCKET: !Ref AudioStorage
          AWS_SQS_QUEUE_URL: !Ref FeedUpdatesQueue
          DB_HOSTNAME: !GetAtt SettingsDB.Endpoint.Address
          DB_HOSTPORT: !GetAtt SettingsDB.Endpoint.Port
    DependsOn:
    - BotInstance
    - AudioStorage
    - FeedUpdatesQueue
    - SettingsDB
